package sk.mathis.stuba.hibernatemapper;
// Generated Apr 29, 2014 5:20:40 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MdsDevice generated by hbm2java
 */
public class MdsDevice  implements java.io.Serializable {


     private Integer idDevice;
     private MdsDeviceModel mdsDeviceModel;
     private String imei;
     private String type;
     private boolean tested;
     private boolean repaired;
     private Set mdsDiagnosises = new HashSet(0);
     private Set mdsTestings = new HashSet(0);
     private Set mdsServiceOrders = new HashSet(0);

    public MdsDevice() {
    }

	
    public MdsDevice(MdsDeviceModel mdsDeviceModel, String imei, String type, boolean tested, boolean repaired) {
        this.mdsDeviceModel = mdsDeviceModel;
        this.imei = imei;
        this.type = type;
        this.tested = tested;
        this.repaired = repaired;
    }
    public MdsDevice(MdsDeviceModel mdsDeviceModel, String imei, String type, boolean tested, boolean repaired, Set mdsDiagnosises, Set mdsTestings, Set mdsServiceOrders) {
       this.mdsDeviceModel = mdsDeviceModel;
       this.imei = imei;
       this.type = type;
       this.tested = tested;
       this.repaired = repaired;
       this.mdsDiagnosises = mdsDiagnosises;
       this.mdsTestings = mdsTestings;
       this.mdsServiceOrders = mdsServiceOrders;
    }
   
    public Integer getIdDevice() {
        return this.idDevice;
    }
    
    public void setIdDevice(Integer idDevice) {
        this.idDevice = idDevice;
    }
    public MdsDeviceModel getMdsDeviceModel() {
        return this.mdsDeviceModel;
    }
    
    public void setMdsDeviceModel(MdsDeviceModel mdsDeviceModel) {
        this.mdsDeviceModel = mdsDeviceModel;
    }
    public String getImei() {
        return this.imei;
    }
    
    public void setImei(String imei) {
        this.imei = imei;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public boolean isTested() {
        return this.tested;
    }
    
    public void setTested(boolean tested) {
        this.tested = tested;
    }
    public boolean isRepaired() {
        return this.repaired;
    }
    
    public void setRepaired(boolean repaired) {
        this.repaired = repaired;
    }
    public Set getMdsDiagnosises() {
        return this.mdsDiagnosises;
    }
    
    public void setMdsDiagnosises(Set mdsDiagnosises) {
        this.mdsDiagnosises = mdsDiagnosises;
    }
    public Set getMdsTestings() {
        return this.mdsTestings;
    }
    
    public void setMdsTestings(Set mdsTestings) {
        this.mdsTestings = mdsTestings;
    }
    public Set getMdsServiceOrders() {
        return this.mdsServiceOrders;
    }
    
    public void setMdsServiceOrders(Set mdsServiceOrders) {
        this.mdsServiceOrders = mdsServiceOrders;
    }




}


