package sk.mathis.stuba.hibernatemapper;
// Generated Apr 29, 2014 5:20:40 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MdsDeviceVendor generated by hbm2java
 */
public class MdsDeviceVendor  implements java.io.Serializable {


     private Integer idDeviceVendor;
     private String vendor;
     private Set mdsDeviceModels = new HashSet(0);

    public MdsDeviceVendor() {
    }

	
    public MdsDeviceVendor(String vendor) {
        this.vendor = vendor;
    }
    public MdsDeviceVendor(String vendor, Set mdsDeviceModels) {
       this.vendor = vendor;
       this.mdsDeviceModels = mdsDeviceModels;
    }
   
    public Integer getIdDeviceVendor() {
        return this.idDeviceVendor;
    }
    
    public void setIdDeviceVendor(Integer idDeviceVendor) {
        this.idDeviceVendor = idDeviceVendor;
    }
    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }
    public Set getMdsDeviceModels() {
        return this.mdsDeviceModels;
    }
    
    public void setMdsDeviceModels(Set mdsDeviceModels) {
        this.mdsDeviceModels = mdsDeviceModels;
    }




}


