package sk.mathis.stuba.hibernatemapper;
// Generated Apr 29, 2014 5:20:40 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MdsDiagnostician generated by hbm2java
 */
public class MdsDiagnostician  implements java.io.Serializable {


     private Integer idDiagnostician;
     private String name;
     private Set mdsSentDeviceses = new HashSet(0);
     private Set mdsTestings = new HashSet(0);
     private Set mdsInvoices = new HashSet(0);
     private Set mdsRepairs = new HashSet(0);
     private Set mdsDiagnosises = new HashSet(0);

    public MdsDiagnostician() {
    }

	
    public MdsDiagnostician(String name) {
        this.name = name;
    }
    public MdsDiagnostician(String name, Set mdsSentDeviceses, Set mdsTestings, Set mdsInvoices, Set mdsRepairs, Set mdsDiagnosises) {
       this.name = name;
       this.mdsSentDeviceses = mdsSentDeviceses;
       this.mdsTestings = mdsTestings;
       this.mdsInvoices = mdsInvoices;
       this.mdsRepairs = mdsRepairs;
       this.mdsDiagnosises = mdsDiagnosises;
    }
   
    public Integer getIdDiagnostician() {
        return this.idDiagnostician;
    }
    
    public void setIdDiagnostician(Integer idDiagnostician) {
        this.idDiagnostician = idDiagnostician;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getMdsSentDeviceses() {
        return this.mdsSentDeviceses;
    }
    
    public void setMdsSentDeviceses(Set mdsSentDeviceses) {
        this.mdsSentDeviceses = mdsSentDeviceses;
    }
    public Set getMdsTestings() {
        return this.mdsTestings;
    }
    
    public void setMdsTestings(Set mdsTestings) {
        this.mdsTestings = mdsTestings;
    }
    public Set getMdsInvoices() {
        return this.mdsInvoices;
    }
    
    public void setMdsInvoices(Set mdsInvoices) {
        this.mdsInvoices = mdsInvoices;
    }
    public Set getMdsRepairs() {
        return this.mdsRepairs;
    }
    
    public void setMdsRepairs(Set mdsRepairs) {
        this.mdsRepairs = mdsRepairs;
    }
    public Set getMdsDiagnosises() {
        return this.mdsDiagnosises;
    }
    
    public void setMdsDiagnosises(Set mdsDiagnosises) {
        this.mdsDiagnosises = mdsDiagnosises;
    }




}


