package sk.mathis.stuba.hibernatemapper;
// Generated Apr 29, 2014 5:20:40 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MdsDiagnosis generated by hbm2java
 */
public class MdsDiagnosis  implements java.io.Serializable {


     private Integer idDiagnosis;
     private MdsDevice mdsDevice;
     private MdsDiagnostician mdsDiagnostician;
     private String specification;
     private Date setTime;
     private Set mdsRepairs = new HashSet(0);

    public MdsDiagnosis() {
    }

	
    public MdsDiagnosis(MdsDevice mdsDevice, MdsDiagnostician mdsDiagnostician, String specification, Date setTime) {
        this.mdsDevice = mdsDevice;
        this.mdsDiagnostician = mdsDiagnostician;
        this.specification = specification;
        this.setTime = setTime;
    }
    public MdsDiagnosis(MdsDevice mdsDevice, MdsDiagnostician mdsDiagnostician, String specification, Date setTime, Set mdsRepairs) {
       this.mdsDevice = mdsDevice;
       this.mdsDiagnostician = mdsDiagnostician;
       this.specification = specification;
       this.setTime = setTime;
       this.mdsRepairs = mdsRepairs;
    }
   
    public Integer getIdDiagnosis() {
        return this.idDiagnosis;
    }
    
    public void setIdDiagnosis(Integer idDiagnosis) {
        this.idDiagnosis = idDiagnosis;
    }
    public MdsDevice getMdsDevice() {
        return this.mdsDevice;
    }
    
    public void setMdsDevice(MdsDevice mdsDevice) {
        this.mdsDevice = mdsDevice;
    }
    public MdsDiagnostician getMdsDiagnostician() {
        return this.mdsDiagnostician;
    }
    
    public void setMdsDiagnostician(MdsDiagnostician mdsDiagnostician) {
        this.mdsDiagnostician = mdsDiagnostician;
    }
    public String getSpecification() {
        return this.specification;
    }
    
    public void setSpecification(String specification) {
        this.specification = specification;
    }
    public Date getSetTime() {
        return this.setTime;
    }
    
    public void setSetTime(Date setTime) {
        this.setTime = setTime;
    }
    public Set getMdsRepairs() {
        return this.mdsRepairs;
    }
    
    public void setMdsRepairs(Set mdsRepairs) {
        this.mdsRepairs = mdsRepairs;
    }




}


