package sk.mathis.stuba.hibernatemapper;
// Generated Apr 29, 2014 5:20:40 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * MdsInvoice generated by hbm2java
 */
public class MdsInvoice  implements java.io.Serializable {


     private Integer idInvoice;
     private MdsRepair mdsRepair;
     private MdsDiagnostician mdsDiagnostician;
     private double price;
     private Date date;
     private boolean paid;

    public MdsInvoice() {
    }

    public MdsInvoice(MdsRepair mdsRepair, MdsDiagnostician mdsDiagnostician, double price, Date date, boolean paid) {
       this.mdsRepair = mdsRepair;
       this.mdsDiagnostician = mdsDiagnostician;
       this.price = price;
       this.date = date;
       this.paid = paid;
    }
   
    public Integer getIdInvoice() {
        return this.idInvoice;
    }
    
    public void setIdInvoice(Integer idInvoice) {
        this.idInvoice = idInvoice;
    }
    public MdsRepair getMdsRepair() {
        return this.mdsRepair;
    }
    
    public void setMdsRepair(MdsRepair mdsRepair) {
        this.mdsRepair = mdsRepair;
    }
    public MdsDiagnostician getMdsDiagnostician() {
        return this.mdsDiagnostician;
    }
    
    public void setMdsDiagnostician(MdsDiagnostician mdsDiagnostician) {
        this.mdsDiagnostician = mdsDiagnostician;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public boolean isPaid() {
        return this.paid;
    }
    
    public void setPaid(boolean paid) {
        this.paid = paid;
    }




}


