package sk.mathis.stuba.hibernatemapper;
// Generated Apr 29, 2014 5:20:40 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MdsRepair generated by hbm2java
 */
public class MdsRepair  implements java.io.Serializable {


     private Integer idRepair;
     private MdsDiagnosis mdsDiagnosis;
     private MdsDiagnostician mdsDiagnostician;
     private Date startTime;
     private Date endTime;
     private String report;
     private double repairCosts;
     private Set mdsSentDeviceses = new HashSet(0);
     private Set mdsInvoices = new HashSet(0);

    public MdsRepair() {
    }

	
    public MdsRepair(MdsDiagnosis mdsDiagnosis, MdsDiagnostician mdsDiagnostician, Date startTime, double repairCosts) {
        this.mdsDiagnosis = mdsDiagnosis;
        this.mdsDiagnostician = mdsDiagnostician;
        this.startTime = startTime;
        this.repairCosts = repairCosts;
    }
    public MdsRepair(MdsDiagnosis mdsDiagnosis, MdsDiagnostician mdsDiagnostician, Date startTime, Date endTime, String report, double repairCosts, Set mdsSentDeviceses, Set mdsInvoices) {
       this.mdsDiagnosis = mdsDiagnosis;
       this.mdsDiagnostician = mdsDiagnostician;
       this.startTime = startTime;
       this.endTime = endTime;
       this.report = report;
       this.repairCosts = repairCosts;
       this.mdsSentDeviceses = mdsSentDeviceses;
       this.mdsInvoices = mdsInvoices;
    }
   
    public Integer getIdRepair() {
        return this.idRepair;
    }
    
    public void setIdRepair(Integer idRepair) {
        this.idRepair = idRepair;
    }
    public MdsDiagnosis getMdsDiagnosis() {
        return this.mdsDiagnosis;
    }
    
    public void setMdsDiagnosis(MdsDiagnosis mdsDiagnosis) {
        this.mdsDiagnosis = mdsDiagnosis;
    }
    public MdsDiagnostician getMdsDiagnostician() {
        return this.mdsDiagnostician;
    }
    
    public void setMdsDiagnostician(MdsDiagnostician mdsDiagnostician) {
        this.mdsDiagnostician = mdsDiagnostician;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public String getReport() {
        return this.report;
    }
    
    public void setReport(String report) {
        this.report = report;
    }
    public double getRepairCosts() {
        return this.repairCosts;
    }
    
    public void setRepairCosts(double repairCosts) {
        this.repairCosts = repairCosts;
    }
    public Set getMdsSentDeviceses() {
        return this.mdsSentDeviceses;
    }
    
    public void setMdsSentDeviceses(Set mdsSentDeviceses) {
        this.mdsSentDeviceses = mdsSentDeviceses;
    }
    public Set getMdsInvoices() {
        return this.mdsInvoices;
    }
    
    public void setMdsInvoices(Set mdsInvoices) {
        this.mdsInvoices = mdsInvoices;
    }




}


