package sk.mathis.stuba.hibernatemapper;
// Generated Apr 29, 2014 5:20:40 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MdsServiceClaimant generated by hbm2java
 */
public class MdsServiceClaimant  implements java.io.Serializable {


     private Integer idServiceClaimant;
     private String name;
     private String adress;
     private String city;
     private String country;
     private String email;
     private String phoneNumber;
     private String legalType;
     private Set mdsServiceOrders = new HashSet(0);

    public MdsServiceClaimant() {
    }

	
    public MdsServiceClaimant(String name, String adress, String city, String country, String email, String phoneNumber, String legalType) {
        this.name = name;
        this.adress = adress;
        this.city = city;
        this.country = country;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.legalType = legalType;
    }
    public MdsServiceClaimant(String name, String adress, String city, String country, String email, String phoneNumber, String legalType, Set mdsServiceOrders) {
       this.name = name;
       this.adress = adress;
       this.city = city;
       this.country = country;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.legalType = legalType;
       this.mdsServiceOrders = mdsServiceOrders;
    }
   
    public Integer getIdServiceClaimant() {
        return this.idServiceClaimant;
    }
    
    public void setIdServiceClaimant(Integer idServiceClaimant) {
        this.idServiceClaimant = idServiceClaimant;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getLegalType() {
        return this.legalType;
    }
    
    public void setLegalType(String legalType) {
        this.legalType = legalType;
    }
    public Set getMdsServiceOrders() {
        return this.mdsServiceOrders;
    }
    
    public void setMdsServiceOrders(Set mdsServiceOrders) {
        this.mdsServiceOrders = mdsServiceOrders;
    }




}


