package sk.mathis.stuba.hibernatemapper;
// Generated Apr 29, 2014 5:20:40 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * MdsServiceOrder generated by hbm2java
 */
public class MdsServiceOrder  implements java.io.Serializable {


     private Integer idServiceOrder;
     private MdsServiceClaimant mdsServiceClaimant;
     private MdsDevice mdsDevice;
     private Date registrationDate;
     private String faultDescription;
     private boolean deviceSent;

    public MdsServiceOrder() {
    }

    public MdsServiceOrder(MdsServiceClaimant mdsServiceClaimant, MdsDevice mdsDevice, Date registrationDate, String faultDescription, boolean deviceSent) {
       this.mdsServiceClaimant = mdsServiceClaimant;
       this.mdsDevice = mdsDevice;
       this.registrationDate = registrationDate;
       this.faultDescription = faultDescription;
       this.deviceSent = deviceSent;
    }
   
    public Integer getIdServiceOrder() {
        return this.idServiceOrder;
    }
    
    public void setIdServiceOrder(Integer idServiceOrder) {
        this.idServiceOrder = idServiceOrder;
    }
    public MdsServiceClaimant getMdsServiceClaimant() {
        return this.mdsServiceClaimant;
    }
    
    public void setMdsServiceClaimant(MdsServiceClaimant mdsServiceClaimant) {
        this.mdsServiceClaimant = mdsServiceClaimant;
    }
    public MdsDevice getMdsDevice() {
        return this.mdsDevice;
    }
    
    public void setMdsDevice(MdsDevice mdsDevice) {
        this.mdsDevice = mdsDevice;
    }
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
    public String getFaultDescription() {
        return this.faultDescription;
    }
    
    public void setFaultDescription(String faultDescription) {
        this.faultDescription = faultDescription;
    }
    public boolean isDeviceSent() {
        return this.deviceSent;
    }
    
    public void setDeviceSent(boolean deviceSent) {
        this.deviceSent = deviceSent;
    }




}


