package sk.mathis.stuba.hibernatemapper;
// Generated Apr 29, 2014 5:20:40 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * MdsSentDevices generated by hbm2java
 */
public class MdsSentDevices  implements java.io.Serializable {


     private Integer idSentDevices;
     private MdsRepair mdsRepair;
     private MdsDiagnostician mdsDiagnostician;
     private Date sentDate;

    public MdsSentDevices() {
    }

    public MdsSentDevices(MdsRepair mdsRepair, MdsDiagnostician mdsDiagnostician, Date sentDate) {
       this.mdsRepair = mdsRepair;
       this.mdsDiagnostician = mdsDiagnostician;
       this.sentDate = sentDate;
    }
   
    public Integer getIdSentDevices() {
        return this.idSentDevices;
    }
    
    public void setIdSentDevices(Integer idSentDevices) {
        this.idSentDevices = idSentDevices;
    }
    public MdsRepair getMdsRepair() {
        return this.mdsRepair;
    }
    
    public void setMdsRepair(MdsRepair mdsRepair) {
        this.mdsRepair = mdsRepair;
    }
    public MdsDiagnostician getMdsDiagnostician() {
        return this.mdsDiagnostician;
    }
    
    public void setMdsDiagnostician(MdsDiagnostician mdsDiagnostician) {
        this.mdsDiagnostician = mdsDiagnostician;
    }
    public Date getSentDate() {
        return this.sentDate;
    }
    
    public void setSentDate(Date sentDate) {
        this.sentDate = sentDate;
    }




}


