package sk.mathis.stuba.hibernatemapper;
// Generated Apr 29, 2014 5:20:40 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MdsTesting generated by hbm2java
 */
public class MdsTesting  implements java.io.Serializable {


     private Integer idTesting;
     private MdsDevice mdsDevice;
     private MdsDiagnostician mdsDiagnostician;
     private Date startTime;
     private Date endTime;
     private Set mdsTests = new HashSet(0);

    public MdsTesting() {
    }

	
    public MdsTesting(MdsDevice mdsDevice, MdsDiagnostician mdsDiagnostician, Date startTime) {
        this.mdsDevice = mdsDevice;
        this.mdsDiagnostician = mdsDiagnostician;
        this.startTime = startTime;
    }
    public MdsTesting(MdsDevice mdsDevice, MdsDiagnostician mdsDiagnostician, Date startTime, Date endTime, Set mdsTests) {
       this.mdsDevice = mdsDevice;
       this.mdsDiagnostician = mdsDiagnostician;
       this.startTime = startTime;
       this.endTime = endTime;
       this.mdsTests = mdsTests;
    }
   
    public Integer getIdTesting() {
        return this.idTesting;
    }
    
    public void setIdTesting(Integer idTesting) {
        this.idTesting = idTesting;
    }
    public MdsDevice getMdsDevice() {
        return this.mdsDevice;
    }
    
    public void setMdsDevice(MdsDevice mdsDevice) {
        this.mdsDevice = mdsDevice;
    }
    public MdsDiagnostician getMdsDiagnostician() {
        return this.mdsDiagnostician;
    }
    
    public void setMdsDiagnostician(MdsDiagnostician mdsDiagnostician) {
        this.mdsDiagnostician = mdsDiagnostician;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public Set getMdsTests() {
        return this.mdsTests;
    }
    
    public void setMdsTests(Set mdsTests) {
        this.mdsTests = mdsTests;
    }




}


