package sk.mathis.stuba.hibernatemapper;
// Generated Apr 29, 2014 5:20:40 PM by Hibernate Tools 3.6.0



/**
 * MdsTest generated by hbm2java
 */
public class MdsTest  implements java.io.Serializable {


     private Integer idTest;
     private MdsTesting mdsTesting;
     private String type;
     private String foundFault;

    public MdsTest() {
    }

    public MdsTest(MdsTesting mdsTesting, String type, String foundFault) {
       this.mdsTesting = mdsTesting;
       this.type = type;
       this.foundFault = foundFault;
    }
   
    public Integer getIdTest() {
        return this.idTest;
    }
    
    public void setIdTest(Integer idTest) {
        this.idTest = idTest;
    }
    public MdsTesting getMdsTesting() {
        return this.mdsTesting;
    }
    
    public void setMdsTesting(MdsTesting mdsTesting) {
        this.mdsTesting = mdsTesting;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getFoundFault() {
        return this.foundFault;
    }
    
    public void setFoundFault(String foundFault) {
        this.foundFault = foundFault;
    }




}


